additionalRepositories:
  - url: https://github.com/OSPRS/DataDonation.git
    checkoutLocation: datadonation
  - url: https://github.com/OSPRS/QuestionnaireEngine.git
    checkoutLocation: QuestionnaireEngine

workspaceLocation: QuestionnaireApp/OSPRS.code-workspace
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      npm install
      npm run prepare-charite
    command: npm start

  - name: Database
    command: |
      cd /workspace/datadonation
      docker-compose up
      gp sync-done database
    openMode: tab-after

  - name: Backend
    init: | 
      dotnet tool install --global dotnet-ef
      export PATH="$PATH:$HOME/.dotnet/tools/"
      cd /workspace/datadonation
      dotnet restore
    command: |
      gp sync-await database
      cd /workspace/datadonation/api
      dotnet watch run
    openMode: split-right
  
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3333
    onOpen: ignore
  - port: 5000
    onOpen: ignore
  - port: 5001
    onOpen: ignore

image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - esbenp.prettier-vscode
    - k--kato.docomment
    - muhammad-sammy.csharp
    - humao.rest-client

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true