additionalRepositories:
  - url: https://github.com/OSPRS/DataDonation.git
    checkoutLocation: datadonation
  - url: https://github.com/OSPRS/QuestionnaireEngine.git
    checkoutLocation: QuestionnaireEngine

workspaceLocation: QuestionnaireApp/OSPRS.code-workspace
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      npm install
      npm run prepare-charite
    command: npm start
  - name: Backend
    before: | 
      dotnet tool install --global dotnet-ef
      export PATH="$PATH:$HOME/.dotnet/tools/"
      cd /workspace/datadonation
      dotnet restore
    command: |
      cd /workspace/datadonation
      dotnet restore
      docker-compose up -d
      sleep 10
      cd api
      dotnet watch run
    openMode: split-right
  
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3333
    onOpen: ignore
  - port: 5000
    onOpen: ignore
  - port: 5001
    onOpen: ignore

image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - esbenp.prettier-vscode
    - k--kato.docomment
    - https://github.com/OmniSharp/omnisharp-vscode/releases/download/v1.23.12/csharp-1.23.12.vsix

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true